---
- hosts: all
  vars_files:
  - env_variables 
  tasks:
  - name: getenforce status
    command: getenforce
    register: getenforce_result
    changed_when: "'disabled' not in getenforce_result.stdout|lower"
    become: yes

  - name: Set setenforce to zero
    command: setenforce 0
    when: getenforce_result is changed
    become: yes

  - name: Disable SELINUX property
    selinux:
      conf: /etc/selinux/config
      state: disabled
    notify: reboot system
    when: getenforce_result is changed
    become: yes

  - name: Installing required packages
    yum:
     name: "{{ item }}"
     state: present
    with_items: "{{ packages }}"
    become: yes

  - name: ntp to Euro clock
    shell: "ntpdate time.enlib"
    ignore_errors: yes
    become: yes
  
  - name: "hwclock to sysclock"
    shell: "hwclock --systohc"
    become: yes

  #- name: Starting and Enabling the required services
  #  service:
  #   name: "{{ item }}"
  #   state: started
  #   enabled: yes
  #  with_items: "{{ services }}"
  #  become: yes
  #    key: "{{ lookup('v6tmed', '/root/.ssh/authorized_keys') }}"

  - name: make .ssh direcotry
    become: yes
    file:
      path: "/root/.ssh"
      state: directory
      mode: '0600'
  - name: Copy keys file
    become: yes
    copy:
      src: authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: '0600'
#  - name: create empty file
#    become: yes
#    file:
#      path: "/root/.ssh/authorized_keys"
#      state: touch
#      mode: '0600'
#
#  - name: put pubkey
#    become: yes
#    lineinfile:
#      path: "/root/.ssh/authorized_keys"
#      line: "{{ pubkey }}"
#  - name: Check/create fetch directory
#    file:
#      path: "{{ item }}"
#      state: directory
#    with_items: "{{ fetch_dir }}"

  handlers:
    - name: reboot system
      reboot:
      become: yes
